### ISSUE TITLE
Where to download the blender_data for testing?

### ISSUE THREAD

**Issue by 3togo** [dayjaby/dibr-rvs#1]
Where to download the blender_data for testing?

**Comment by dayjaby** [comment]
Hey, thanks for being interested in this project!

I am currently uploading it to google drive and let you know once it's
finished (> 2gb of data) This project was my final master thesis in
university. So I could offer you a pdf of the thesis as well if you want to
know what's going on ;)

Edit: You can download it here: https://drive.google.com/open?id=1F_8IbcVMp3HFLM2ZCs4QaXrdiJgZw1Y-

Most of the work is done in
https://github.com/dayjaby/dibr-rvs/blob/master/common/dibr.py It's a bit
cryptic and non-documented...so don't hesitate to ask any questions!

In sincerely
David Jablonski (dayjaby@gmail.com)

**Comment by 3togo** [comment]
Hi David,

Downloading blender_data now.
Will there be any rgb_data as well?

Many thanks

Joe

**Comment by dayjaby** [comment]
The rgb_data was another set of real-world test data, but without astonishing results, mainly due to the lack of any usable calibration data. blender_data is a virtual scene made in blender, where it's of course easier to extract the exact camera parameters. So for test purposes I'd recommend to stick to blender_data :)
